apiVersion: v1
kind: Service
metadata:
  labels:
    app: saree-gateway-service
  name: saree-gateway-service
spec:
  selector:
    app: saree-gateway
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 9290
    nodePort: 30013
    protocol: TCP
